on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.jsh | jshell -
        - uses: actions/setup-java@main
          with:
              java-version: ${{env.JAVA}}
              distribution: zulu
        - run: |
              curl https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem > DigiCertGlobalRootCA.crt.pem
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              gradle --warning-mode all copyDependencies
              javac -Xlint:deprecation -cp copyDependencies/*:. Server.java
              docker build -t chaowenguo/vertx .
              docker push chaowenguo/vertx
              #sudo apt install -y --no-install-recommends miredo
              #sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no root@2a01:4f8:211:25cf::2196:1 'docker stop `docker container ls -q`;
              #docker system prune -af;
              #docker network create --ipv6 --subnet fd10::/64 backend;
              #docker run -d --name redis --network backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes;
              #docker run -d --name web --network backend chaowenguo/vertx;
              #docker run -d --name ingress --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
              #sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no root@2a01:4f8:211:25cf::2196:1 'docker stop `docker container ls -q`;
              #docker system prune -af;
              #docker network create --ipv6 --subnet fd10::/64 backend;
              #docker run -d --name redis --network backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes;
              #docker run -d --name web --network backend chaowenguo/vertx;
              #docker run -d --name ingress --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              ssh -o StrictHostKeyChecking=no -i key ubuntu@155.248.198.227 'sudo docker stop `sudo docker container ls -q`;
              sudo docker system prune -af;
              sudo docker network create backend;
              sudo docker run -d --name redis --network backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes;
              sudo docker run -d --name web --network backend chaowenguo/vertx;
              sudo docker run -d --name ingress --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}      
