on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - run: |
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              gradle --warning-mode all copyDependencies
              jar xf copyDependencies/netty-tcnative-*-linux-x86_64.jar META-INF/native
              cp META-INF/native/* copyDependencies
              rm -rf META-INF copyDependencies/netty-tcnative-*-linux-x86_64.jar
              javac -Xlint:deprecation -cp copyDependencies/*:. Server.java
              docker build -t chaowenguo/spring .
              docker push chaowenguo/spring
              sudo apt install -y --no-install-recommends miredo
              sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no root@2a01:4f8:242:4986:face:face:100c:0001 'docker network create --ipv6 --subnet fd10::/64 backend;
              docker run -d --name web --network backend -p 80:80 chaowenguo/spring'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}      
