on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - run: |
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              gradle copyDependencies
              javac -cp copyDependencies/*:. Server.java
              docker build -t chaowenguo/spring .
              docker push chaowenguo/spring
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              ssh -o StrictHostKeyChecking=no -i key ubuntu@150.230.43.249 'sudo docker network create backend;
              sudo docker run -d --name redis --network backend redis;
              sudo docker run -d --name web --network backend chaowenguo/spring'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}      
